export const POST_LIST_REQUEST = 'POST_LIST_REQUEST';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';
export const POST_LIST_ERROR = 'POST_LIST_ERROR';

export const POST_DETAIL_REQUEST = 'POST_DETAIL_REQUEST';
export const POST_DETAIL_SUCCESS = 'POST_DETAIL_SUCCESS';
export const POST_DETAIL_ERROR = 'POST_DETAIL_ERROR';

export const POST_DELETE_REQUEST = 'POST_DETAIL_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DETAIL_SUCCESS';
export const POST_DELETE_ERROR = 'POST_DETAIL_ERROR';

export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_ERROR = 'POST_CREATE_ERROR';
